apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: kustomize-guestbook-ui
  name: kustomize-guestbook-ui
spec:
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: guestbook-ui
    weight: 100
