apiVersion: route.openshift.io/v1
kind: Route
metadata:
  #labels:
    #app: guestbook-ui
  name: guestbook-ui
spec:
  host: kustomize-guestbook-ui.apps.<ingress_domain>
  port:
      targetPort: 80
  to:
    kind: Service
    name: kustomize-guestbook-ui
    weight: 100
